# Generated by Django 3.1.1 on 2020-10-02 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_view',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 15, 24, 1, 338881)),
        ),
        migrations.AddField(
            model_name='blog',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
