# Generated by Django 2.2.5 on 2020-11-25 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201002_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_view',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 20, 55, 52, 215244)),
        ),
    ]
