# Generated by Django 2.2.5 on 2020-09-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200922_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.URLField(blank=True, default='https://i.ibb.co/8P7ycd3/devops-3155973-1920.jpg', null=True),
        ),
    ]
